spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KevinYangKai/springcloud.git
          username: KevinYangKai
          password: yk19950102
          search-paths: /config-repo
server:
  port: 2001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka